<?php

return [

    // Uncomment the languages that your site supports - or add new ones.
    // These are sorted by the native name, which is the order you might show them in a language selector.
    // Regional languages are sorted by their base language, so "British English" sorts as "English, British"
    'avalaibleLocales' => [
        ['locale' => 'af', 'name'  => 'Afrikaans',              'script'                    => 'Latn', 'native' => 'Afrikaans', 'regional'            => 'af_ZA'],
        ['locale' => 'agq', 'name' => 'Aghem',                  'script'                    => 'Latn', 'native' => 'Aghem', 'regional'                => ''],
        ['locale' => 'ak', 'name'  => 'Akan',                   'script'                    => 'Latn', 'native' => 'Akan', 'regional'                 => 'ak_GH'],
        ['locale' => 'an', 'name'  => 'Aragonese',              'script'                    => 'Latn', 'native' => 'aragonés', 'regional'             => 'an_ES'],
        ['locale' => 'cch', 'name' => 'Atsam',                  'script'                    => 'Latn', 'native' => 'Atsam', 'regional'                => ''],
        ['locale' => 'gn', 'name'  => 'Guaraní',                'script'                    => 'Latn', 'native' => 'Avañe’ẽ', 'regional'              => ''],
        ['locale' => 'ae', 'name'  => 'Avestan',                'script'                    => 'Latn', 'native' => 'avesta', 'regional'               => ''],
        ['locale' => 'ay', 'name'  => 'Aymara',                 'script'                    => 'Latn', 'native' => 'aymar aru', 'regional'            => 'ay_PE'],
        ['locale' => 'az', 'name'  => 'Azerbaijani (Latin)',    'script'                    => 'Latn', 'native' => 'azərbaycanca', 'regional'         => 'az_AZ'],
        ['locale' => 'id', 'name'  => 'Indonesian',             'script'                    => 'Latn', 'native' => 'Bahasa Indonesia', 'regional'     => 'id_ID'],
        ['locale' => 'ms', 'name'  => 'Malay',                  'script'                    => 'Latn', 'native' => 'Bahasa Melayu', 'regional'        => 'ms_MY'],
        ['locale' => 'bm', 'name'  => 'Bambara',                'script'                    => 'Latn', 'native' => 'bamanakan', 'regional'            => ''],
        ['locale' => 'jv', 'name'  => 'Javanese (Latin)',       'script'                    => 'Latn', 'native' => 'Basa Jawa', 'regional'            => ''],
        ['locale' => 'su', 'name'  => 'Sundanese',              'script'                    => 'Latn', 'native' => 'Basa Sunda', 'regional'           => ''],
        ['locale' => 'bh', 'name'  => 'Bihari',                 'script'                    => 'Latn', 'native' => 'Bihari', 'regional'               => ''],
        ['locale' => 'bi', 'name'  => 'Bislama',                'script'                    => 'Latn', 'native' => 'Bislama', 'regional'              => ''],
        ['locale' => 'nb', 'name'  => 'Norwegian Bokmål',       'script'                    => 'Latn', 'native' => 'Bokmål', 'regional'               => 'nb_NO'],
        ['locale' => 'bs', 'name'  => 'Bosnian',                'script'                    => 'Latn', 'native' => 'bosanski', 'regional'             => 'bs_BA'],
        ['locale' => 'br', 'name'  => 'Breton',                 'script'                    => 'Latn', 'native' => 'brezhoneg', 'regional'            => 'br_FR'],
        ['locale' => 'ca', 'name'  => 'Catalan',                'script'                    => 'Latn', 'native' => 'català', 'regional'               => 'ca_ES'],
        ['locale' => 'ch', 'name'  => 'Chamorro',               'script'                    => 'Latn', 'native' => 'Chamoru', 'regional'              => ''],
        ['locale' => 'ny', 'name'  => 'Chewa',                  'script'                    => 'Latn', 'native' => 'chiCheŵa', 'regional'             => ''],
        ['locale' => 'kde', 'name' => 'Makonde',                'script'                    => 'Latn', 'native' => 'Chimakonde', 'regional'           => ''],
        ['locale' => 'sn', 'name'  => 'Shona',                  'script'                    => 'Latn', 'native' => 'chiShona', 'regional'             => ''],
        ['locale' => 'co', 'name'  => 'Corsican',               'script'                    => 'Latn', 'native' => 'corsu', 'regional'                => ''],
        ['locale' => 'cy', 'name'  => 'Welsh',                  'script'                    => 'Latn', 'native' => 'Cymraeg', 'regional'              => 'cy_GB'],
        ['locale' => 'da', 'name'  => 'Danish',                 'script'                    => 'Latn', 'native' => 'dansk', 'regional'                => 'da_DK'],
        ['locale' => 'se', 'name'  => 'Northern Sami',          'script'                    => 'Latn', 'native' => 'davvisámegiella', 'regional'      => 'se_NO'],
        ['locale' => 'de', 'name'  => 'German',                 'script'                    => 'Latn', 'native' => 'Deutsch', 'regional'              => 'de_DE'],
        ['locale' => 'luo', 'name' => 'Luo',                    'script'                    => 'Latn', 'native' => 'Dholuo', 'regional'               => ''],
        ['locale' => 'nv', 'name'  => 'Navajo',                 'script'                    => 'Latn', 'native' => 'Diné bizaad', 'regional'          => ''],
        ['locale' => 'dua', 'name' => 'Duala',                  'script'                    => 'Latn', 'native' => 'duálá', 'regional'                => ''],
        ['locale' => 'et', 'name'  => 'Estonian',               'script'                    => 'Latn', 'native' => 'eesti', 'regional'                => 'et_EE'],
        ['locale' => 'na', 'name'  => 'Nauru',                  'script'                    => 'Latn', 'native' => 'Ekakairũ Naoero', 'regional'      => ''],
        ['locale' => 'guz', 'name' => 'Ekegusii',               'script'                    => 'Latn', 'native' => 'Ekegusii', 'regional'             => ''],
        ['locale' => 'en', 'name'  => 'English',                'script'                    => 'Latn', 'native' => 'English', 'regional'              => 'en_GB'],
        ['locale' => 'es', 'name'  => 'Spanish',                'script'                    => 'Latn', 'native' => 'español', 'regional'              => 'es_ES'],
        ['locale' => 'eo', 'name'  => 'Esperanto',              'script'                    => 'Latn', 'native' => 'esperanto', 'regional'            => ''],
        ['locale' => 'eu', 'name'  => 'Basque',                 'script'                    => 'Latn', 'native' => 'euskara', 'regional'              => 'eu_ES'],
        ['locale' => 'ewo', 'name' => 'Ewondo',                 'script'                    => 'Latn', 'native' => 'ewondo', 'regional'               => ''],
        ['locale' => 'ee', 'name'  => 'Ewe',                    'script'                    => 'Latn', 'native' => 'eʋegbe', 'regional'               => ''],
        ['locale' => 'fil', 'name' => 'Filipino',               'script'                    => 'Latn', 'native' => 'Filipino', 'regional'             => 'fil_PH'],
        ['locale' => 'fr', 'name'  => 'French',                 'script'                    => 'Latn', 'native' => 'français', 'regional'             => 'fr_FR'],
        ['locale' => 'fy', 'name'  => 'Western Frisian',        'script'                    => 'Latn', 'native' => 'frysk', 'regional'                => 'fy_DE'],
        ['locale' => 'fur', 'name' => 'Friulian',               'script'                    => 'Latn', 'native' => 'furlan', 'regional'               => 'fur_IT'],
        ['locale' => 'fo', 'name'  => 'Faroese',                'script'                    => 'Latn', 'native' => 'føroyskt', 'regional'             => 'fo_FO'],
        ['locale' => 'gaa', 'name' => 'Ga',                     'script'                    => 'Latn', 'native' => 'Ga', 'regional'                   => ''],
        ['locale' => 'ga', 'name'  => 'Irish',                  'script'                    => 'Latn', 'native' => 'Gaeilge', 'regional'              => 'ga_IE'],
        ['locale' => 'gv', 'name'  => 'Manx',                   'script'                    => 'Latn', 'native' => 'Gaelg', 'regional'                => 'gv_GB'],
        ['locale' => 'sm', 'name'  => 'Samoan',                 'script'                    => 'Latn', 'native' => 'Gagana fa’a Sāmoa', 'regional'    => ''],
        ['locale' => 'gl', 'name'  => 'Galician',               'script'                    => 'Latn', 'native' => 'galego', 'regional'               => 'gl_ES'],
        ['locale' => 'ki', 'name'  => 'Kikuyu',                 'script'                    => 'Latn', 'native' => 'Gikuyu', 'regional'               => ''],
        ['locale' => 'gd', 'name'  => 'Scottish Gaelic',        'script'                    => 'Latn', 'native' => 'Gàidhlig', 'regional'             => 'gd_GB'],
        ['locale' => 'ha', 'name'  => 'Hausa',                  'script'                    => 'Latn', 'native' => 'Hausa', 'regional'                => 'ha_NG'],
        ['locale' => 'bez', 'name' => 'Bena',                   'script'                    => 'Latn', 'native' => 'Hibena', 'regional'               => ''],
        ['locale' => 'ho', 'name'  => 'Hiri Motu',              'script'                    => 'Latn', 'native' => 'Hiri Motu', 'regional'            => ''],
        ['locale' => 'hr', 'name'  => 'Croatian',               'script'                    => 'Latn', 'native' => 'hrvatski', 'regional'             => 'hr_HR'],
        ['locale' => 'bem', 'name' => 'Bemba',                  'script'                    => 'Latn', 'native' => 'Ichibemba', 'regional'            => 'bem_ZM'],
        ['locale' => 'io', 'name'  => 'Ido',                    'script'                    => 'Latn', 'native' => 'Ido', 'regional'                  => ''],
        ['locale' => 'ig', 'name'  => 'Igbo',                   'script'                    => 'Latn', 'native' => 'Igbo', 'regional'                 => 'ig_NG'],
        ['locale' => 'rn', 'name'  => 'Rundi',                  'script'                    => 'Latn', 'native' => 'Ikirundi', 'regional'             => ''],
        ['locale' => 'ia', 'name'  => 'Interlingua',            'script'                    => 'Latn', 'native' => 'interlingua', 'regional'          => 'ia_FR'],
        ['locale' => 'sbp', 'name' => 'Sileibi',                'script'                    => 'Latn', 'native' => 'Ishisangu', 'regional'            => ''],
        ['locale' => 'nd', 'name'  => 'North Ndebele',          'script'                    => 'Latn', 'native' => 'isiNdebele', 'regional'           => ''],
        ['locale' => 'nr', 'name'  => 'South Ndebele',          'script'                    => 'Latn', 'native' => 'isiNdebele', 'regional'           => 'nr_ZA'],
        ['locale' => 'xh', 'name'  => 'Xhosa',                  'script'                    => 'Latn', 'native' => 'isiXhosa', 'regional'             => 'xh_ZA'],
        ['locale' => 'zu', 'name'  => 'Zulu',                   'script'                    => 'Latn', 'native' => 'isiZulu', 'regional'              => 'zu_ZA'],
        ['locale' => 'it', 'name'  => 'Italian',                'script'                    => 'Latn', 'native' => 'italiano', 'regional'             => 'it_IT'],
        ['locale' => 'ik', 'name'  => 'Inupiaq',                'script'                    => 'Latn', 'native' => 'Iñupiaq', 'regional'              => 'ik_CA'],
        ['locale' => 'dyo', 'name' => 'Jola-Fonyi',             'script'                    => 'Latn', 'native' => 'joola', 'regional'                => ''],
        ['locale' => 'kea', 'name' => 'Kabuverdianu',           'script'                    => 'Latn', 'native' => 'kabuverdianu', 'regional'         => ''],
        ['locale' => 'kaj', 'name' => 'Jju',                    'script'                    => 'Latn', 'native' => 'Kaje', 'regional'                 => ''],
        ['locale' => 'mh', 'name'  => 'Marshallese',            'script'                    => 'Latn', 'native' => 'Kajin M̧ajeļ', 'regional'         => 'mh_MH'],
        ['locale' => 'kl', 'name'  => 'Kalaallisut',            'script'                    => 'Latn', 'native' => 'kalaallisut', 'regional'          => 'kl_GL'],
        ['locale' => 'kln', 'name' => 'Kalenjin',               'script'                    => 'Latn', 'native' => 'Kalenjin', 'regional'             => ''],
        ['locale' => 'kr', 'name'  => 'Kanuri',                 'script'                    => 'Latn', 'native' => 'Kanuri', 'regional'               => ''],
        ['locale' => 'kcg', 'name' => 'Tyap',                   'script'                    => 'Latn', 'native' => 'Katab', 'regional'                => ''],
        ['locale' => 'kw', 'name'  => 'Cornish',                'script'                    => 'Latn', 'native' => 'kernewek', 'regional'             => 'kw_GB'],
        ['locale' => 'naq', 'name' => 'Nama',                   'script'                    => 'Latn', 'native' => 'Khoekhoegowab', 'regional'        => ''],
        ['locale' => 'rof', 'name' => 'Rombo',                  'script'                    => 'Latn', 'native' => 'Kihorombo', 'regional'            => ''],
        ['locale' => 'kam', 'name' => 'Kamba',                  'script'                    => 'Latn', 'native' => 'Kikamba', 'regional'              => ''],
        ['locale' => 'kg', 'name'  => 'Kongo',                  'script'                    => 'Latn', 'native' => 'Kikongo', 'regional'              => ''],
        ['locale' => 'jmc', 'name' => 'Machame',                'script'                    => 'Latn', 'native' => 'Kimachame', 'regional'            => ''],
        ['locale' => 'rw', 'name'  => 'Kinyarwanda',            'script'                    => 'Latn', 'native' => 'Kinyarwanda', 'regional'          => 'rw_RW'],
        ['locale' => 'asa', 'name' => 'Kipare',                 'script'                    => 'Latn', 'native' => 'Kipare', 'regional'               => ''],
        ['locale' => 'rwk', 'name' => 'Rwa',                    'script'                    => 'Latn', 'native' => 'Kiruwa', 'regional'               => ''],
        ['locale' => 'saq', 'name' => 'Samburu',                'script'                    => 'Latn', 'native' => 'Kisampur', 'regional'             => ''],
        ['locale' => 'ksb', 'name' => 'Shambala',               'script'                    => 'Latn', 'native' => 'Kishambaa', 'regional'            => ''],
        ['locale' => 'swc', 'name' => 'Congo Swahili',          'script'                    => 'Latn', 'native' => 'Kiswahili ya Kongo', 'regional'   => ''],
        ['locale' => 'sw', 'name'  => 'Swahili',                'script'                    => 'Latn', 'native' => 'Kiswahili', 'regional'            => 'sw_KE'],
        ['locale' => 'dav', 'name' => 'Dawida',                 'script'                    => 'Latn', 'native' => 'Kitaita', 'regional'              => ''],
        ['locale' => 'teo', 'name' => 'Teso',                   'script'                    => 'Latn', 'native' => 'Kiteso', 'regional'               => ''],
        ['locale' => 'khq', 'name' => 'Koyra Chiini',           'script'                    => 'Latn', 'native' => 'Koyra ciini', 'regional'          => ''],
        ['locale' => 'ses', 'name' => 'Songhay',                'script'                    => 'Latn', 'native' => 'Koyraboro senni', 'regional'      => ''],
        ['locale' => 'mfe', 'name' => 'Morisyen',               'script'                    => 'Latn', 'native' => 'kreol morisien', 'regional'       => ''],
        ['locale' => 'ht', 'name'  => 'Haitian',                'script'                    => 'Latn', 'native' => 'Kreyòl ayisyen', 'regional'       => 'ht_HT'],
        ['locale' => 'kj', 'name'  => 'Kuanyama',               'script'                    => 'Latn', 'native' => 'Kwanyama', 'regional'             => ''],
        ['locale' => 'ksh', 'name' => 'Kölsch',                 'script'                    => 'Latn', 'native' => 'Kölsch', 'regional'               => ''],
        ['locale' => 'ebu', 'name' => 'Kiembu',                 'script'                    => 'Latn', 'native' => 'Kĩembu', 'regional'               => ''],
        ['locale' => 'mer', 'name' => 'Kimîîru',                'script'                    => 'Latn', 'native' => 'Kĩmĩrũ', 'regional'               => ''],
        ['locale' => 'lag', 'name' => 'Langi',                  'script'                    => 'Latn', 'native' => 'Kɨlaangi', 'regional'             => ''],
        ['locale' => 'lah', 'name' => 'Lahnda',                 'script'                    => 'Latn', 'native' => 'Lahnda', 'regional'               => ''],
        ['locale' => 'la', 'name'  => 'Latin',                  'script'                    => 'Latn', 'native' => 'latine', 'regional'               => ''],
        ['locale' => 'lv', 'name'  => 'Latvian',                'script'                    => 'Latn', 'native' => 'latviešu', 'regional'             => 'lv_LV'],
        ['locale' => 'to', 'name'  => 'Tongan',                 'script'                    => 'Latn', 'native' => 'lea fakatonga', 'regional'        => ''],
        ['locale' => 'lt', 'name'  => 'Lithuanian',             'script'                    => 'Latn', 'native' => 'lietuvių', 'regional'             => 'lt_LT'],
        ['locale' => 'li', 'name'  => 'Limburgish',             'script'                    => 'Latn', 'native' => 'Limburgs', 'regional'             => 'li_BE'],
        ['locale' => 'ln', 'name'  => 'Lingala',                'script'                    => 'Latn', 'native' => 'lingála', 'regional'              => ''],
        ['locale' => 'lg', 'name'  => 'Ganda',                  'script'                    => 'Latn', 'native' => 'Luganda', 'regional'              => 'lg_UG'],
        ['locale' => 'luy', 'name' => 'Oluluyia',               'script'                    => 'Latn', 'native' => 'Luluhia', 'regional'              => ''],
        ['locale' => 'lb', 'name'  => 'Luxembourgish',          'script'                    => 'Latn', 'native' => 'Lëtzebuergesch', 'regional'       => 'lb_LU'],
        ['locale' => 'hu', 'name'  => 'Hungarian',              'script'                    => 'Latn', 'native' => 'magyar', 'regional'               => 'hu_HU'],
        ['locale' => 'mgh', 'name' => 'Makhuwa-Meetto',         'script'                    => 'Latn', 'native' => 'Makua', 'regional'                => ''],
        ['locale' => 'mg', 'name'  => 'Malagasy',               'script'                    => 'Latn', 'native' => 'Malagasy', 'regional'             => 'mg_MG'],
        ['locale' => 'mt', 'name'  => 'Maltese',                'script'                    => 'Latn', 'native' => 'Malti', 'regional'                => 'mt_MT'],
        ['locale' => 'mtr', 'name' => 'Mewari',                 'script'                    => 'Latn', 'native' => 'Mewari', 'regional'               => ''],
        ['locale' => 'mua', 'name' => 'Mundang',                'script'                    => 'Latn', 'native' => 'Mundang', 'regional'              => ''],
        ['locale' => 'mi', 'name'  => 'Māori',                  'script'                    => 'Latn', 'native' => 'Māori', 'regional'                => 'mi_NZ'],
        ['locale' => 'nl', 'name'  => 'Dutch',                  'script'                    => 'Latn', 'native' => 'Nederlands', 'regional'           => 'nl_NL'],
        ['locale' => 'nmg', 'name' => 'Kwasio',                 'script'                    => 'Latn', 'native' => 'ngumba', 'regional'               => ''],
        ['locale' => 'yav', 'name' => 'Yangben',                'script'                    => 'Latn', 'native' => 'nuasue', 'regional'               => ''],
        ['locale' => 'nn', 'name'  => 'Norwegian Nynorsk',      'script'                    => 'Latn', 'native' => 'nynorsk', 'regional'              => 'nn_NO'],
        ['locale' => 'oc', 'name'  => 'Occitan',                'script'                    => 'Latn', 'native' => 'occitan', 'regional'              => 'oc_FR'],
        ['locale' => 'ang', 'name' => 'Old English',            'script'                    => 'Runr', 'native' => 'Old English', 'regional'          => ''],
        ['locale' => 'xog', 'name' => 'Soga',                   'script'                    => 'Latn', 'native' => 'Olusoga', 'regional'              => ''],
        ['locale' => 'om', 'name'  => 'Oromo',                  'script'                    => 'Latn', 'native' => 'Oromoo', 'regional'               => 'om_ET'],
        ['locale' => 'ng', 'name'  => 'Ndonga',                 'script'                    => 'Latn', 'native' => 'OshiNdonga', 'regional'           => ''],
        ['locale' => 'hz', 'name'  => 'Herero',                 'script'                    => 'Latn', 'native' => 'Otjiherero', 'regional'           => ''],
        ['locale' => 'nds', 'name' => 'Low German',             'script'                    => 'Latn', 'native' => 'Plattdüütsch', 'regional'         => 'nds_DE'],
        ['locale' => 'pl', 'name'  => 'Polish',                 'script'                    => 'Latn', 'native' => 'polski', 'regional'               => 'pl_PL'],
        ['locale' => 'ff', 'name'  => 'Fulah',                  'script'                    => 'Latn', 'native' => 'Pulaar', 'regional'               => 'ff_SN'],
        ['locale' => 'pi', 'name'  => 'Pahari-Potwari',         'script'                    => 'Latn', 'native' => 'Pāli', 'regional'                 => ''],
        ['locale' => 'aa', 'name'  => 'Afar',                   'script'                    => 'Latn', 'native' => 'Qafar', 'regional'                => 'aa_ER'],
        ['locale' => 'ty', 'name'  => 'Tahitian',               'script'                    => 'Latn', 'native' => 'Reo Māohi', 'regional'            => ''],
        ['locale' => 'ksf', 'name' => 'Bafia',                  'script'                    => 'Latn', 'native' => 'rikpa', 'regional'                => ''],
        ['locale' => 'ro', 'name'  => 'Romanian',               'script'                    => 'Latn', 'native' => 'română', 'regional'               => 'ro_RO'],
        ['locale' => 'cgg', 'name' => 'Chiga',                  'script'                    => 'Latn', 'native' => 'Rukiga', 'regional'               => ''],
        ['locale' => 'rm', 'name'  => 'Romansh',                'script'                    => 'Latn', 'native' => 'rumantsch', 'regional'            => ''],
        ['locale' => 'qu', 'name'  => 'Quechua',                'script'                    => 'Latn', 'native' => 'Runa Simi', 'regional'            => ''],
        ['locale' => 'nyn', 'name' => 'Nyankole',               'script'                    => 'Latn', 'native' => 'Runyankore', 'regional'           => ''],
        ['locale' => 'ssy', 'name' => 'Saho',                   'script'                    => 'Latn', 'native' => 'Saho', 'regional'                 => ''],
        ['locale' => 'sc', 'name'  => 'Sardinian',              'script'                    => 'Latn', 'native' => 'sardu', 'regional'                => 'sc_IT'],
        ['locale' => 'gsw', 'name' => 'Swiss German',           'script'                    => 'Latn', 'native' => 'Schwiizertüütsch', 'regional'     => ''],
        ['locale' => 'trv', 'name' => 'Taroko',                 'script'                    => 'Latn', 'native' => 'Seediq', 'regional'               => ''],
        ['locale' => 'seh', 'name' => 'Sena',                   'script'                    => 'Latn', 'native' => 'sena', 'regional'                 => ''],
        ['locale' => 'nso', 'name' => 'Northern Sotho',         'script'                    => 'Latn', 'native' => 'Sesotho sa Leboa', 'regional'     => 'nso_ZA'],
        ['locale' => 'st', 'name'  => 'Southern Sotho',         'script'                    => 'Latn', 'native' => 'Sesotho', 'regional'              => 'st_ZA'],
        ['locale' => 'tn', 'name'  => 'Tswana',                 'script'                    => 'Latn', 'native' => 'Setswana', 'regional'             => 'tn_ZA'],
        ['locale' => 'sq', 'name'  => 'Albanian',               'script'                    => 'Latn', 'native' => 'shqip', 'regional'                => 'sq_AL'],
        ['locale' => 'sid', 'name' => 'Sidamo',                 'script'                    => 'Latn', 'native' => 'Sidaamu Afo', 'regional'          => 'sid_ET'],
        ['locale' => 'ss', 'name'  => 'Swati',                  'script'                    => 'Latn', 'native' => 'Siswati', 'regional'              => 'ss_ZA'],
        ['locale' => 'sk', 'name'  => 'Slovak',                 'script'                    => 'Latn', 'native' => 'slovenčina', 'regional'           => 'sk_SK'],
        ['locale' => 'sl', 'name'  => 'Slovene',                'script'                    => 'Latn', 'native' => 'slovenščina', 'regional'          => 'sl_SI'],
        ['locale' => 'so', 'name'  => 'Somali',                 'script'                    => 'Latn', 'native' => 'Soomaali', 'regional'             => 'so_SO'],
        ['locale' => 'sh', 'name'  => 'Serbo-Croatian',         'script'                    => 'Latn', 'native' => 'srpskohrvatski', 'regional'       => ''],
        ['locale' => 'fi', 'name'  => 'Finnish',                'script'                    => 'Latn', 'native' => 'suomi', 'regional'                => 'fi_FI'],
        ['locale' => 'sv', 'name'  => 'Swedish',                'script'                    => 'Latn', 'native' => 'svenska', 'regional'              => 'sv_SE'],
        ['locale' => 'sg', 'name'  => 'Sango',                  'script'                    => 'Latn', 'native' => 'Sängö', 'regional'                => ''],
        ['locale' => 'tl', 'name'  => 'Tagalog',                'script'                    => 'Latn', 'native' => 'Tagalog', 'regional'              => 'tl_PH'],
        ['locale' => 'kab', 'name' => 'Kabyle',                 'script'                    => 'Latn', 'native' => 'Taqbaylit', 'regional'            => 'kab_DZ'],
        ['locale' => 'twq', 'name' => 'Tasawaq',                'script'                    => 'Latn', 'native' => 'Tasawaq senni', 'regional'        => ''],
        ['locale' => 'shi', 'name' => 'Tachelhit (Latin)',      'script'                    => 'Latn', 'native' => 'Tashelhit', 'regional'            => ''],
        ['locale' => 'nus', 'name' => 'Nuer',                   'script'                    => 'Latn', 'native' => 'Thok Nath', 'regional'            => ''],
        ['locale' => 'vi', 'name'  => 'Vietnamese',             'script'                    => 'Latn', 'native' => 'Tiếng Việt', 'regional'           => 'vi_VN'],
        ['locale' => 'lu', 'name'  => 'Luba-Katanga',           'script'                    => 'Latn', 'native' => 'Tshiluba', 'regional'             => 've_ZA'],
        ['locale' => 've', 'name'  => 'Venda',                  'script'                    => 'Latn', 'native' => 'Tshivenḓa', 'regional'            => ''],
        ['locale' => 'tw', 'name'  => 'Twi',                    'script'                    => 'Latn', 'native' => 'Twi', 'regional'                  => ''],
        ['locale' => 'tr', 'name'  => 'Turkish',                'script'                    => 'Latn', 'native' => 'Türkçe', 'regional'               => 'tr_TR'],
        ['locale' => 'ale', 'name' => 'Aleut',                  'script'                    => 'Latn', 'native' => 'Unangax tunuu', 'regional'        => ''],
        ['locale' => 'vo', 'name'  => 'Volapük',                'script'                    => 'Latn', 'native' => 'Volapük', 'regional'              => ''],
        ['locale' => 'fj', 'name'  => 'Fijian',                 'script'                    => 'Latn', 'native' => 'vosa Vakaviti', 'regional'        => ''],
        ['locale' => 'wa', 'name'  => 'Walloon',                'script'                    => 'Latn', 'native' => 'Walon', 'regional'                => 'wa_BE'],
        ['locale' => 'wae', 'name' => 'Walser',                 'script'                    => 'Latn', 'native' => 'Walser', 'regional'               => 'wae_CH'],
        ['locale' => 'wen', 'name' => 'Sorbian',                'script'                    => 'Latn', 'native' => 'Wendic', 'regional'               => ''],
        ['locale' => 'wo', 'name'  => 'Wolof',                  'script'                    => 'Latn', 'native' => 'Wolof', 'regional'                => 'wo_SN'],
        ['locale' => 'ts', 'name'  => 'Tsonga',                 'script'                    => 'Latn', 'native' => 'Xitsonga', 'regional'             => 'ts_ZA'],
        ['locale' => 'dje', 'name' => 'Zarma',                  'script'                    => 'Latn', 'native' => 'Zarmaciine', 'regional'           => ''],
        ['locale' => 'yo', 'name'  => 'Yoruba',                 'script'                    => 'Latn', 'native' => 'Èdè Yorùbá', 'regional'           => 'yo_NG'],
        ['locale' => 'is', 'name'  => 'Icelandic',              'script'                    => 'Latn', 'native' => 'íslenska', 'regional'             => 'is_IS'],
        ['locale' => 'cs', 'name'  => 'Czech',                  'script'                    => 'Latn', 'native' => 'čeština', 'regional'              => 'cs_CZ'],
        ['locale' => 'bas', 'name' => 'Basa',                   'script'                    => 'Latn', 'native' => 'Ɓàsàa', 'regional'                => ''],
        ['locale' => 'mas', 'name' => 'Masai',                  'script'                    => 'Latn', 'native' => 'ɔl-Maa', 'regional'               => ''],
        ['locale' => 'haw', 'name' => 'Hawaiian',               'script'                    => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi', 'regional'       => ''],
        ['locale' => 'el', 'name'  => 'Greek',                  'script'                    => 'Grek', 'native' => 'Ελληνικά', 'regional'             => 'el_GR'],
        ['locale' => 'uz', 'name'  => 'Uzbek (Cyrillic)',       'script'                    => 'Cyrl', 'native' => 'Ўзбек', 'regional'                => 'uz_UZ'],
        ['locale' => 'ab', 'name'  => 'Abkhazian',              'script'                    => 'Cyrl', 'native' => 'Аҧсуа', 'regional'                => ''],
        ['locale' => 'os', 'name'  => 'Ossetic',                'script'                    => 'Cyrl', 'native' => 'Ирон', 'regional'                 => 'os_RU'],
        ['locale' => 'ky', 'name'  => 'Kyrgyz',                 'script'                    => 'Cyrl', 'native' => 'Кыргыз', 'regional'               => 'ky_KG'],
        ['locale' => 'sr', 'name'  => 'Serbian (Cyrillic)',     'script'                    => 'Cyrl', 'native' => 'Српски', 'regional'               => 'sr_RS'],
        ['locale' => 'av', 'name'  => 'Avaric',                 'script'                    => 'Cyrl', 'native' => 'авар мацӀ', 'regional'            => ''],
        ['locale' => 'ady', 'name' => 'Adyghe',                 'script'                    => 'Cyrl', 'native' => 'адыгэбзэ', 'regional'             => ''],
        ['locale' => 'ba', 'name'  => 'Bashkir',                'script'                    => 'Cyrl', 'native' => 'башҡорт теле', 'regional'         => ''],
        ['locale' => 'be', 'name'  => 'Belarusian',             'script'                    => 'Cyrl', 'native' => 'беларуская', 'regional'           => 'be_BY'],
        ['locale' => 'bg', 'name'  => 'Bulgarian',              'script'                    => 'Cyrl', 'native' => 'български', 'regional'            => 'bg_BG'],
        ['locale' => 'kv', 'name'  => 'Komi',                   'script'                    => 'Cyrl', 'native' => 'коми кыв', 'regional'             => ''],
        ['locale' => 'mk', 'name'  => 'Macedonian',             'script'                    => 'Cyrl', 'native' => 'македонски', 'regional'           => 'mk_MK'],
        ['locale' => 'mn', 'name'  => 'Mongolian (Cyrillic)',   'script'                    => 'Cyrl', 'native' => 'монгол', 'regional'               => 'mn_MN'],
        ['locale' => 'ce', 'name'  => 'Chechen',                'script'                    => 'Cyrl', 'native' => 'нохчийн мотт', 'regional'         => 'ce_RU'],
        ['locale' => 'ru', 'name'  => 'Russian',                'script'                    => 'Cyrl', 'native' => 'русский', 'regional'              => 'ru_RU'],
        ['locale' => 'sah', 'name' => 'Yakut',                  'script'                    => 'Cyrl', 'native' => 'саха тыла', 'regional'            => ''],
        ['locale' => 'tt', 'name'  => 'Tatar',                  'script'                    => 'Cyrl', 'native' => 'татар теле', 'regional'           => 'tt_RU'],
        ['locale' => 'tg', 'name'  => 'Tajik (Cyrillic)',       'script'                    => 'Cyrl', 'native' => 'тоҷикӣ', 'regional'               => 'tg_TJ'],
        ['locale' => 'tk', 'name'  => 'Turkmen',                'script'                    => 'Cyrl', 'native' => 'түркменче', 'regional'            => 'tk_TM'],
        ['locale' => 'uk', 'name'  => 'Ukrainian',              'script'                    => 'Cyrl', 'native' => 'українська', 'regional'           => 'uk_UA'],
        ['locale' => 'cv', 'name'  => 'Chuvash',                'script'                    => 'Cyrl', 'native' => 'чӑваш чӗлхи', 'regional'          => 'cv_RU'],
        ['locale' => 'cu', 'name'  => 'Church Slavic',          'script'                    => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ', 'regional'     => ''],
        ['locale' => 'kk', 'name'  => 'Kazakh',                 'script'                    => 'Cyrl', 'native' => 'қазақ тілі', 'regional'           => 'kk_KZ'],
        ['locale' => 'hy', 'name'  => 'Armenian',               'script'                    => 'Armn', 'native' => 'Հայերեն', 'regional'              => 'hy_AM'],
        ['locale' => 'yi', 'name'  => 'Yiddish',                'script'                    => 'Hebr', 'native' => 'ייִדיש', 'regional'               => 'yi_US'],
        ['locale' => 'he', 'name'  => 'Hebrew',                 'script'                    => 'Hebr', 'native' => 'עברית', 'regional'                => 'he_IL'],
        ['locale' => 'ug', 'name'  => 'Uyghur',                 'script'                    => 'Arab', 'native' => 'ئۇيغۇرچە', 'regional'             => 'ug_CN'],
        ['locale' => 'ur', 'name'  => 'Urdu',                   'script'                    => 'Arab', 'native' => 'اردو', 'regional'                 => 'ur_PK'],
        ['locale' => 'ar', 'name'  => 'Arabic',                 'script'                    => 'Arab', 'native' => 'العربية', 'regional'              => 'ar_AE'],
        ['locale' => 'sd', 'name'  => 'Sindhi',                 'script'                    => 'Arab', 'native' => 'سنڌي', 'regional'                 => 'sd_IN'],
        ['locale' => 'fa', 'name'  => 'Persian',                'script'                    => 'Arab', 'native' => 'فارسی', 'regional'                => 'fa_IR'],
        ['locale' => 'ps', 'name'  => 'Pashto',                 'script'                    => 'Arab', 'native' => 'پښتو', 'regional'                 => 'ps_AF'],
        ['locale' => 'ks', 'name'  => 'Kashmiri (Arabic)',      'script'                    => 'Arab', 'native' => 'کأشُر', 'regional'                => 'ks_IN'],
        ['locale' => 'ku', 'name'  => 'Kurdish',                'script'                    => 'Arab', 'native' => 'کوردی', 'regional'                => 'ku_TR'],
        ['locale' => 'dv', 'name'  => 'Divehi',                 'script'                    => 'Thaa', 'native' => 'ދިވެހިބަސް', 'regional'           => 'dv_MV'],
        ['locale' => 'kok', 'name' => 'Konkani',                'script'                    => 'Deva', 'native' => 'कोंकणी', 'regional'               => 'kok_IN'],
        ['locale' => 'doi', 'name' => 'Dogri',                  'script'                    => 'Deva', 'native' => 'डोगरी', 'regional'                => 'doi_IN'],
        ['locale' => 'ne', 'name'  => 'Nepali',                 'script'                    => 'Deva', 'native' => 'नेपाली', 'regional'               => ''],
        ['locale' => 'pra', 'name' => 'Prakrit',                'script'                    => 'Deva', 'native' => 'प्राकृत', 'regional'              => ''],
        ['locale' => 'brx', 'name' => 'Bodo',                   'script'                    => 'Deva', 'native' => 'बड़ो', 'regional'                 => 'brx_IN'],
        ['locale' => 'bra', 'name' => 'Braj',                   'script'                    => 'Deva', 'native' => 'ब्रज भाषा', 'regional'            => ''],
        ['locale' => 'mr', 'name'  => 'Marathi',                'script'                    => 'Deva', 'native' => 'मराठी', 'regional'                => 'mr_IN'],
        ['locale' => 'mai', 'name' => 'Maithili',               'script'                    => 'Tirh', 'native' => 'मैथिली', 'regional'               => 'mai_IN'],
        ['locale' => 'raj', 'name' => 'Rajasthani',             'script'                    => 'Deva', 'native' => 'राजस्थानी', 'regional'            => ''],
        ['locale' => 'sa', 'name'  => 'Sanskrit',               'script'                    => 'Deva', 'native' => 'संस्कृतम्', 'regional'            => 'sa_IN'],
        ['locale' => 'hi', 'name'  => 'Hindi',                  'script'                    => 'Deva', 'native' => 'हिन्दी', 'regional'               => 'hi_IN'],
        ['locale' => 'as', 'name'  => 'Assamese',               'script'                    => 'Beng', 'native' => 'অসমীয়া', 'regional'              => 'as_IN'],
        ['locale' => 'bn', 'name'  => 'Bengali',                'script'                    => 'Beng', 'native' => 'বাংলা', 'regional'                => 'bn_BD'],
        ['locale' => 'mni', 'name' => 'Manipuri',               'script'                    => 'Beng', 'native' => 'মৈতৈ', 'regional'                 => 'mni_IN'],
        ['locale' => 'pa', 'name'  => 'Punjabi (Gurmukhi)',     'script'                    => 'Guru', 'native' => 'ਪੰਜਾਬੀ', 'regional'               => 'pa_IN'],
        ['locale' => 'gu', 'name'  => 'Gujarati',               'script'                    => 'Gujr', 'native' => 'ગુજરાતી', 'regional'              => 'gu_IN'],
        ['locale' => 'or', 'name'  => 'Oriya',                  'script'                    => 'Orya', 'native' => 'ଓଡ଼ିଆ', 'regional'                => 'or_IN'],
        ['locale' => 'ta', 'name'  => 'Tamil',                  'script'                    => 'Taml', 'native' => 'தமிழ்', 'regional'                => 'ta_IN'],
        ['locale' => 'te', 'name'  => 'Telugu',                 'script'                    => 'Telu', 'native' => 'తెలుగు', 'regional'               => 'te_IN'],
        ['locale' => 'kn', 'name'  => 'Kannada',                'script'                    => 'Knda', 'native' => 'ಕನ್ನಡ', 'regional'                => 'kn_IN'],
        ['locale' => 'ml', 'name'  => 'Malayalam',              'script'                    => 'Mlym', 'native' => 'മലയാളം', 'regional'               => 'ml_IN'],
        ['locale' => 'si', 'name'  => 'Sinhala',                'script'                    => 'Sinh', 'native' => 'සිංහල', 'regional'                => 'si_LK'],
        ['locale' => 'th', 'name'  => 'Thai',                   'script'                    => 'Thai', 'native' => 'ไทย', 'regional'                  => 'th_TH'],
        ['locale' => 'lo', 'name'  => 'Lao',                    'script'                    => 'Laoo', 'native' => 'ລາວ', 'regional'                  => 'lo_LA'],
        ['locale' => 'bo', 'name'  => 'Tibetan',                'script'                    => 'Tibt', 'native' => 'པོད་སྐད་', 'regional'             => 'bo_IN'],
        ['locale' => 'dz', 'name'  => 'Dzongkha',               'script'                    => 'Tibt', 'native' => 'རྫོང་ཁ', 'regional'               => 'dz_BT'],
        ['locale' => 'my', 'name'  => 'Burmese',                'script'                    => 'Mymr', 'native' => 'မြန်မာဘာသာ', 'regional'           => 'my_MM'],
        ['locale' => 'ka', 'name'  => 'Georgian',               'script'                    => 'Geor', 'native' => 'ქართული', 'regional'              => 'ka_GE'],
        ['locale' => 'byn', 'name' => 'Blin',                   'script'                    => 'Ethi', 'native' => 'ብሊን', 'regional'                  => 'byn_ER'],
        ['locale' => 'tig', 'name' => 'Tigre',                  'script'                    => 'Ethi', 'native' => 'ትግረ', 'regional'                  => 'tig_ER'],
        ['locale' => 'ti', 'name'  => 'Tigrinya',               'script'                    => 'Ethi', 'native' => 'ትግርኛ', 'regional'                 => 'ti_ET'],
        ['locale' => 'am', 'name'  => 'Amharic',                'script'                    => 'Ethi', 'native' => 'አማርኛ', 'regional'                 => 'am_ET'],
        ['locale' => 'wal', 'name' => 'Wolaytta',               'script'                    => 'Ethi', 'native' => 'ወላይታቱ', 'regional'                => 'wal_ET'],
        ['locale' => 'chr', 'name' => 'Cherokee',               'script'                    => 'Cher', 'native' => 'ᏣᎳᎩ', 'regional'                  => ''],
        ['locale' => 'iu', 'name'  => 'Inuktitut',              'script'                    =>  'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'regional'               => 'iu_CA'],
        ['locale' => 'oj', 'name'  => 'Ojibwa',                 'script'                    => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'regional'             => ''],
        ['locale' => 'cr', 'name'  => 'Cree',                   'script'                    => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'regional'              => ''],
        ['locale' => 'km', 'name'  => 'Khmer',                  'script'                    => 'Khmr', 'native' => 'ភាសាខ្មែរ', 'regional'            => 'km_KH'],
        ['locale' => 'tzm', 'name' => 'Central Atlas Tamazight','script'                    => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional'             => ''],
        ['locale' => 'yue', 'name' => 'Yue',                    'script'                    => 'Hant', 'native' => '廣州話', 'regional'                  => 'yue_HK'],
        ['locale' => 'ja', 'name'  => 'Japanese',               'script'                    => 'Jpan', 'native' => '日本語', 'regional'                  => 'ja_JP'],
        ['locale' => 'zh', 'name'  => 'Chinese (Simplified)',   'script'                    => 'Hans', 'native' => '简体中文', 'regional'                 => 'zh_CN'],
        ['locale' => 'ii', 'name'  => 'Sichuan Yi',             'script'                    => 'Yiii', 'native' => 'ꆈꌠꉙ', 'regional'                  => ''],
        ['locale' => 'vai', 'name' => 'Vai (Vai)',              'script'                    => 'Vaii', 'native' => 'ꕙꔤ', 'regional'                   => ''],
        ['locale' => 'ko', 'name'  => 'Korean',                 'script'                    => 'Hang', 'native' => '한국어', 'regional'                  => 'ko_KR'],
    ],

    'supportedLocales' => [
        'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
        'ar'          => ['name' => 'Arabic',                 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],
    ],

    // Requires middleware `LaravelSessionRedirect.php`.
    //
    // Automatically determine locale from browser (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)
    // on first call if it's not defined in the URL. Redirect user to computed localized url.
    // For example, if users browser language is `de`, and `de` is active in the array `supportedLocales`,
    // the `/about` would be redirected to `/de/about`.
    //
    // The locale will be stored in session and only be computed from browser
    // again if the session expires.
    //
    // If false, system will take app.php locale attribute
    'useAcceptLanguageHeader' => true,

    // If `hideDefaultLocaleInURL` is true, then a url without locale
    // is identical with the same url with default locale.
    // For example, if `en` is default locale, then `/en/about` and `/about`
    // would be identical.
    //
    // If in addition the middleware `LaravelLocalizationRedirectFilter` is active, then
    // every url with default locale is redirected to url without locale.
    // For example, `/en/about` would be redirected to `/about`.
    // It is recommended to use `hideDefaultLocaleInURL` only in
    // combination with the middleware `LaravelLocalizationRedirectFilter`
    // to avoid duplicate content (SEO).
    //
    // If `useAcceptLanguageHeader` is true, then the first time
    // the locale will be determined from browser and redirect to that language.
    // After that, `hideDefaultLocaleInURL` behaves as usual.
    'hideDefaultLocaleInURL' => false,

    // If you want to display the locales in particular order in the language selector you should write the order here.
    //CAUTION: Please consider using the appropriate locale code otherwise it will not work
    //Example: 'localesOrder' => ['es','en'],
    'localesOrder' => ['ar', 'en'],

    //  If you want to use custom lang url segments like 'at' instead of 'de-AT', you can use the mapping to tallow the LanguageNegotiator to assign the descired locales based on HTTP Accept Language Header. For example you want ot use 'at', so map HTTP Accept Language Header 'de-AT' to 'at' (['de-AT' => 'at']).
    'localesMapping' => [],

    // Locale suffix for LC_TIME and LC_MONETARY
    // Defaults to most common ".UTF-8". Set to blank on Windows systems, change to ".utf8" on CentOS and similar.
    'utf8suffix' => env('LARAVELLOCALIZATION_UTF8SUFFIX', '.UTF-8'),

    // URLs which should not be processed, e.g. '/nova', '/nova/*', '/nova-api/*' or specific application URLs
    // Defaults to []
    'urlsIgnored' => ['/skipped'],

];
